
#ifndef _CREDENTIALS_
#define _CREDENTIALS_

#define THINGSBOARD_SERVER ""
#define THINGSBOARD_PORT 1883

#define FACTORY_SERVER 0
#define DEMO_SERVER 1

#define THINGSBOARD_PROVISION_SERVER FACTORY_SERVER

#if(THINGSBOARD_PROVISION_SERVER == DEMO_SERVER)
#define PROVISION_DEVICE_KEY ""
#define PROVISION_DEVICE_SECRET ""
#elif (THINGSBOARD_PROVISION_SERVER == FACTORY_SERVER)
#define PROVISION_DEVICE_KEY ""
#define PROVISION_DEVICE_SECRET ""
#endif

#define ssid ""
#define wifiPassword ""
#endif // _CREDENTIALS_
