// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: in3ator_display

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc1 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Arc1, 218);
    lv_obj_set_height(ui_Arc1, 220);
    lv_obj_set_x(ui_Arc1, 201);
    lv_obj_set_y(ui_Arc1, -76);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_Arc1, 50);


    ui_Button1 = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 142);
    lv_obj_set_height(ui_Button1, 83);
    lv_obj_set_x(ui_Button1, -265);
    lv_obj_set_y(ui_Button1, -116);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BUTTONLABEL = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_BUTTONLABEL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BUTTONLABEL, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BUTTONLABEL, -221);
    lv_obj_set_y(ui_BUTTONLABEL, -13);
    lv_obj_set_align(ui_BUTTONLABEL, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BUTTONLABEL, "PUSH ME");

    ui_Slider1 = lv_slider_create(ui_Screen1);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 244);
    lv_obj_set_height(ui_Slider1, 62);
    lv_obj_set_x(ui_Slider1, -187);
    lv_obj_set_y(ui_Slider1, 92);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);


    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Slider1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Slider1,
                                                                                              lv_obj_get_style_pad_right(ui_Slider1, LV_PART_MAIN) + 1, LV_PART_MAIN);

}
